spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://xxxx'
    username: root
    password: 12345
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
